# Use root/example as user/password credentials
services:

  node-red:
    container_name: iot-node-red
    build:
      context: ./nodered-custom/
      dockerfile: Dockerfile
    image: custom_nodered:latest
    environment:
      - TZ=Europe/Amsterdam
      - MYSQLUSERNAME=root
      - MYSQLPASSWORD=example
    ports:
      - "1880:1880"
    networks:
      iot-net:
        ipv4_address: 172.16.0.100
    volumes:
      - ./nodered-custom/data:/data


  mosquitto:
    container_name: iot-mosquitto
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      iot-net:
        ipv4_address: 172.16.0.101
    ports:
    - "1883:1883" 


  influxdb:
    container_name: iot-influxdb
    image: influxdb:2.7.4
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234!
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=se4iot
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Ga8nVsXP4FAe5_M1a5j7uCa4zO_u_M9oUsO8wUSWh_wPbR3clc9ZTv420Li9adOVCPl1tGvn6hLHfI5gP7Lm5A==
    networks:
      iot-net:
        ipv4_address: 172.16.0.104


  grafana:
    image: grafana/grafana
    container_name: iot-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/:/var/lib/grafana
    networks:
      iot-net:
        ipv4_address: 172.16.0.108

  sensor-simulation:
    container_name: iot-sensor-simulation
    build:
      context: ./sensor-simulation/
      dockerfile: Dockerfile
    image: sensor-simulation:latest
    environment:
      - MQTT_SERVER_URI=tcp://iot-mosquitto:1883
      - MQTT_SERVER_USERNAME=
      - MQTT_SERVER_PASSWORD=
      - MQTT_SERVER_TOPIC=smart-sensors
      - SENSOR_HUMIDITY_ENABLED=true
      - SENSOR_TEMPERATURE_ENABLED=true
      - SENSOR_SOILMOISTURE_ENABLED=true
      - SENSOR_LIGHTINTENSITY_ENABLED=true
      - SENSOR_LIVESTOCK_ENABLED=true
      - SENSOR_INTERVAL_PERIOD=5
      - NUMBER_FIRMS=2
      - NUMBER_AREAS=3
    networks:
      iot-net:
        ipv4_address: 172.16.0.109
    volumes:
      - ./sensor-simulation/data:/data

  
networks:
  iot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

