apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/project-iot-net: "true"
        io.kompose.service: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto
          name: iot-mosquitto
          ports:
            - containerPort: 1883
              hostPort: 1883
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto-claim0
            - mountPath: /mosquitto/log
              name: mosquitto-claim1
            - mountPath: /mosquitto/data
              name: mosquitto-claim2
      restartPolicy: Always
      volumes:
        - name: mosquitto-claim0
          persistentVolumeClaim:
            claimName: mosquitto-claim0
        - name: mosquitto-claim1
          persistentVolumeClaim:
            claimName: mosquitto-claim1
        - name: mosquitto-claim2
          persistentVolumeClaim:
            claimName: mosquitto-claim2
status: {}
