apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node-red
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-red
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/project-iot-net: "true"
        io.kompose.service: node-red
    spec:
      containers:
        - env:
            - name: MYSQLPASSWORD
              value: example
            - name: MYSQLUSERNAME
              value: root
            - name: TZ
              value: Europe/Amsterdam
          image: custom_nodered:latest
          name: iot-node-red
          ports:
            - containerPort: 1880
              hostPort: 1880
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: node-red-claim0
      restartPolicy: Always
      volumes:
        - name: node-red-claim0
          persistentVolumeClaim:
            claimName: node-red-claim0
status: {}
